spring.application.name=tracker

spring.datasource.url=jdbc:postgresql://localhost:5432/devtrackr
spring.datasource.username=postgres
spring.datasource.password=aW@9v9guuJz

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true